### PR TITLE
Caption position for small screens

### PR DESCRIPTION
**Pull request by ThisDaveHill**

### CODE REVIEW

**Comment by nickpearson-uoy** [comment]
Looks like this undoes an update from a few years ago to "Improve figure width": https://github.com/university-of-york/design-patterns/commit/566f18c756b21d69670c93ed0f34a946d627a0e9#diff-a6b0cc791fb69d05672c33ae4e815940607908537c84304c55100442c71c5880R99-R101

Do you remember what issue that fixed?

**Comment by ThisDaveHill** [comment]
I looked in to it, and I believe that it was a mistake 2 years ago. There's nothing of concern when reinstating the code.

**Comment by nickpearson-uoy** [comment]
👍

**Review by nickpearson-uoy — APPROVED** [review]

**Pull request merged**
