### PR TITLE
Add new rich-tag molecule

### PR DESCRIPTION
**Pull request by FergusMcGlynn**
This PR adds a new "rich tag" molecule that has been designed during the development of the new Course Search application. It was written by Richard Allum (who is on leave w/c 23/11/2020). He noted that:

> ...direct pixel values will also need replacing with variables. The reason this has not yet been done is that the local build server does not compile css on my machine, so the only changes made to reflect the use of sass so far are the breakpoint mixins.

so feel free to make edits/suggestions as appropriate.

### CODE REVIEW

**Comment by nickpearson-uoy** [comment]
I'm going to merge this into `dev` for now - this will also auto-deploy it to the `/preview/` version of the pattern library so we can share it with non-devs. Ie; https://www.york.ac.uk/preview/pattern-library/

**Comment by FergusMcGlynn** [comment]
Thanks Nick. I've had a look at the preview, and the new "rich tags" don't look quite right: https://www.york.ac.uk/preview/pattern-library/css-components/rich-tag.html. Is this an issue with the CSS we've added? Or possibly how preview works?

**Comment by nickpearson-uoy** [comment]
I was just looking at that - it's because the new stylesheet hasn't been included.

I know how to suggest changes to an existing change but not how to add changes in an otherwise unchanged file.

**Comment by FergusMcGlynn** [comment]
I don't know of any way to suggest changes to files that aren't part of a pull request. What is the change that's needed? I could create a new PR for it so that it can be merged in.

**Comment by nickpearson-uoy** [comment]
I submitted a PR to your clone of Richard's clone of the repo: https://github.com/FergusMcGlynn/design-patterns/pull/1 😣

The change in question is here: https://github.com/FergusMcGlynn/design-patterns/pull/1/files#diff-9287279baa02781404d0237d47948841bc8cee8949cc68764d82b114f924e32f - it adds the new rich-tags to the list of imports in the root Sass file.

Subsequently, I've given the `esg-teaching-and-learning` group write access to the pattern library repo - then at least we'll be able to write to branches within it.

**Comment by FergusMcGlynn** [comment]
Thanks Nick - I've opened a new PR on the Design Pattern Library to merge this change into the `dev` branch. Unfortunately it seems to have failed the `yarn build` step, for reasons I don't fully understand yet. Any thoughts?

**Comment by FergusMcGlynn** [comment]
I've fixed that PR - there was a typo (`rich-tags` vs `rich-tag`)

**Comment by nickpearson-uoy** [comment]
Ouch, two mistakes in as many words - that'll teach me for editing files directly on GitHub!

**Comment by FergusMcGlynn** [comment]
Still seeing the sub-optimal rendering of the rich tags on https://www.york.ac.uk/preview/pattern-library/css-components/rich-tag.html - does it take some time to rebuild, or are we missing something else?

**Comment by nickpearson-uoy** [comment]
It does take a good few minutes to deploy - I'm getting a better version now: 

image

**Comment by itspaulkelly** [comment]
I'm not sure about the semantics of this one. It's not really a tag in the traditional sense (http://ui-patterns.com/patterns/Tag) so I don't think that name works, and it's doing a very similar job to the existing [key fact component](https://www.york.ac.uk/pattern-library/css-components/key-fact.html).  

The existing component is mainly used when we want to shout about things like league table rankings, so I can see why we wouldn't use that as it currently stands the course search results.  Do we maybe need a variant of the key fact component that's there for secondary supporting info in places like course listings?

**Comment by mrgibbonsuoy** [comment]
To me the merit in having the different component (as apposed to cloning the key fact component) is that the tag is aimed at having icons and other user interactions in a smaller space. With future developments (audio / video emending) just for example having two different tags types would hold an advantage for both development directions. That's just my thoughts.

**Comment by ncn1** [comment]
Here are the variations required for Course Search - do they all seem like key facts components?
image

**Comment by itspaulkelly** [comment]
Apologies for this one languishing with me for ages. Thought I'd get some thoughts down before we meet this week.

With the way these are presented here, there's a lot of emphasis (size and bolding) on information that's going to be the same for every course in a set of results - eg 'Undergraduate' and 'Starts 2021'. Ditto for the large mortar board and clock icons, they're using a lot of space (and are a very dark colour which draws attention) but not conveying anything about that particular course. On mobile in particular, that's a lot of screen space going to things that don't really help with comparison.

The structure for these doesn't feel quite right either - eg 'Starts 2021' is used as the title of '4 years full-time'. I can see why they're together as they're both related to time, but start date and duration are separate things.

I think the component we need (semantically and visually) is something more like the [Key info component from the Futurelearn design system](https://design-system.futurelearn.com/molecules/metadata). 

image

Specifically:

- Everything has a visual text label (helpful for accessibility but also for making it obvious what's being shown. Eg lots of qualification types look like a random bunch of letters when someone is seeing them for the first time, so saying eg 'Qualification: MMath' would clarify that)
- Labels and Icons are styled to be secondary to the differentiating text so things are easy to compare
- It easily goes between desktop and mobile by switching to a compact style and stacking
- It doesn't introduce lots of extra boxes into the design
- It flexes to fill the space with however many info items are included

We'd then be able to use that for both the course search and the overview section of a [course page](https://www.york.ac.uk/study/undergraduate/courses/bsc-accounting-business-finance-management-abfm/) so there'd be consistency when going between the two - at the moment we're presenting the same sort of metadata there but not using any particular component, it's just a basic grid. And any other place where we're showing data like this, such as accommodation listings.

**Pull request merged**
